# Generated by Django 5.2 on 2025-04-03 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science'), ('HIS', 'History'), ('BIO', 'Biography'), ('FAN', 'Fantasy'), ('ROM', 'Romance'), ('THR', 'Thriller')], default='FIC', max_length=3)),
                ('published_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('page_count', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='deployment__title_cc2865_idx'), models.Index(fields=['author'], name='deployment__author_008132_idx'), models.Index(fields=['genre'], name='deployment__genre_bd791c_idx'), models.Index(fields=['isbn'], name='deployment__isbn_035edf_idx')],
            },
        ),
    ]
